/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blueMotion_CommandJNI */

#ifndef _Included_blueMotion_CommandJNI
#define _Included_blueMotion_CommandJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blueMotion_CommandJNI
 * Method:    muteSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_muteSound
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    pauseKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_pauseKey
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    playKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_playKey
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    nextKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_nextKey
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    previousKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_previousKey
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    increaseSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_increaseSound
  (JNIEnv *, jobject);

/*
 * Class:     blueMotion_CommandJNI
 * Method:    decreaseSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blueMotion_CommandJNI_decreaseSound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
